export const siteConfig = {
  name: "Toluwalope Dada",
  title: "Robotics Engineer",
  description: "Portfolio website of Toluwalope Dada",
  accentColor: "#1d4ed8",
  social: {
    email: "Toluwalopedada1@gmail.com",
    linkedin: "https://linkedin.com/in/tdad",
    twitter: "https://x.com/tdad1992",
    github: "https://github.com/Holluwacryptic",
  },
  aboutMe: "Self Learning robotics engineer, building projects on Fixed-Wing VTOL hybrid Unmanned Aerial Vehicles. Professional graduate mechanical engineer with experience in automation, automobile repair, maintenance operations, supply chain and fleet management.",
  skills: [
    "CAD & CAM",
    "Robotic UAV Development",
    "Programming",
    "Hardware Integration",
  ],
  projects: [
    {
      name: "Simulation of multi-agent UAVs in uncertain environment",
      description: "A Software-in-the-Loop (SITL) simulation project integrating PX4 firmware, Gazebo physics simulator, ROS2 middleware, and QGroundControl for fixed-wing VTOL UAV development. Designed with high-fidelity environment models with wind turbulence, sensor noise, and actuator dynamics. Testing and logging different flight scenarios with varying weather, payloads, and failure modes before hardware deployment.",
      link: "https://github.com/Holluwacryptic/blog",
      skills: ["LinuxOS Ubuntu", "C++", "Python"],
    },
    {
      name: "Machine Learning Development Pipeline for UAV Simulation",
      description: "A complete ML development workflow for UAV systems: collecting and logging 100+ hours of flight data plus 10,000+ camera frames (ROS2/Gazebo); preprocessed using NumPy/Pandas with cleaning, normalization, and 70/15/15 data splits; engineered features via statistical analysis (FFT, PCA) and derived metrics; developed models (LSTM, CNN, DQN, PPO) in TensorFlow/PyTorch with custom loss functions and Optuna hyperparameter tuning; trained on GPU with regularization and TensorBoard monitoring; deployed TensorFlow Lite models to PX4 via ROS2 with <50ms latency; validated across 200+ scenarios with ablation studies; implemented MLOps pipeline with continuous retraining and version control (DVC/MLflow).",
      link: "https://github.com/Holluwacryptic/blog",
      skills: ["LinuxOS Ubuntu", "C++", "Python", "Docker"],
    },
    {
      name: "Fixed-Wing VTOL CAD Design with Multi-Physics Simulation",
      description: "Modeled complete hybrid VTOL platform in Onshape and SolidWorks (1.5m span, 4kg MTOW) with quad-tiltrotor architecture optimized for reconnaissance, cargo delivery, aerial mapping, and emergency response applications",
      link: "https://github.com/Holluwacryptic/blog",
      skills: ["Onshape", "Solidworks"],
    },
  ],
  experience: [
    {
      company: "Tdad Logistic Network",
      title: "Robotic Engineer",
      dateRange: "Jan 2026 - Present",
      bullets: [
        "Designed a comprehensive testing framework combining software-in-the-loop (SITL) simulation with Gazebo, executing 5,000+ automated test scenarios covering diverse weather conditions, sensor failures, and GPS-denied environments achieving 99.5% system reliability before production release",
        "Member of a cross-functional robotics team of 8 engineers (controls, perception, embedded systems) through Agile development cycles, delivering major feature releases over 12 months including autonomous landing system upgrade and multi-drone coordination capability while maintaining 90% operational uptime through phased rollout strategy",
      ],
    },
    {
      company: "Kadosh Mechatronics",
      title: "Embedded Systems Trainee",
      dateRange: "Dec 2025 - Jan 2026",
      bullets: [
        "Integrated ROS2 middleware with PX4 via Micro XRCE-DDS bridge and connected QGroundControl for real-time mission planning and telemetry monitoring",
        "Identified and resolved control system bugs during simulation that could cause in-flight failures if undetected",
        "Testing a simulation build of a cost-effective Software-in-the-Loop test platform using Arduino Uno and PX4 Pixhawk, aimed at reducing hardware testing costs by $5,000 compared to commercial solutions",
        "Developing a custom C firmware for Arduino to emulate 6-DOF IMU and GPS signals, establishing serial communication with Pixhawk at 100Hz update rate",
      ],
    },
    {
      company: "Kadosh Mechatronics",
      title: "Machine Learning Trainee",
      dateRange: "Sept 2025 - Jan 2026",
      bullets: [
        "Pioneered the trainee program of machine learning for engineering professionals. Leveraging the training for developing an ML model for a fixed-wing VTOL drone",
        "Designed an end-to-end SITL pipeline integrating PX4 firmware, Gazebo physics simulator, ROS2 middleware, and QGroundControl for autonomous drone development",
        "Integrated YOLOv5 computer vision model with Gazebo camera plugin for autonomous landing site detection during simulated GPS-denied scenarios",
        "Creating an automated SITL testing framework evaluating ML controllers across 1,000+ flight scenarios with varying weather, payloads, and failure modes",
      ],
    },
  ],
  education: [
    {
      school: "Northwestern University",
      degree: "Modern Robotics: Mechanics, Planning, and Control Specialization",
      dateRange: "2025 - Present",
      achievements: [
        "Graph Theory", 
        "Torque (Physics)", 
        "Automation Engineering", 
        "Machine Controls", 
        "Artificial Intelligence", 
        "Engineering  Calculations & Analysis", 
        "Applied Mathematics", 
        "Control Systems", 
        "Matlab", 
        "Simulation", 
        "Mathematical Modeling", 
        "Mechanics", 
        "Vibrations", 
        "Virtual Environment", 
        "Robotics",
      ],
    },
    {
      school: "Università di Napoli Federico II",
      degree: "Autonomous Aerospace Systems",
      dateRange: "2025 - Present",
      achievements: [
        "System Representation of UAS", 
        "UAS System Architecture", 
        "Simulation Models", 
        "Principles of guidance models", 
        "Path following", 
        "Integrated Navigation in Autonomous Aircraft Systems", 
        "GPS/INS", 
        "Dead Reckoning", 
        "Obstacle detection", 
        "Tracking for UAS", 
        "Open-loop dynamics", 
        "Autopilot Design models", 
        "Altitude-control State Machine",
      ],
    },
    {
      school: "Federal University of Technology Akure",
      degree: "Masters of Science in Mechanical Engineering",
      dateRange: "2021 - 2025",
      achievements: [
        "Completed 500+ hours of coursework",
        "Began to build 10+ portfolio projects",
        "Hardware integration of software welding platform",
        "Specialized in Automation, Welding and Programming",
      ],
    },
    {
      school: "Federal University of Technology Akure",
      degree: "Bachelors of Science in Mechanical Engineering",
      dateRange: "2014 - 2019",
      achievements: [
        "Departmental Soccer Coach",
        "Engineering faculty stakeholder",
        "Course Representative",
      ],
    },
  ],
};
